name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      run: | 
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        sudo rm -rf /var/lib/apt/lists/*



    - name: "Setup Maven"
      run: |
        echo "Installing Maven"
        sudo apt-get update
        sudo apt-get install -y maven
        sudo rm -rf /var/lib/apt/lists/*

    - name: changing to source
      run: cd demo
    - name: Build with Maven
      run:  mvn clean install
    - name: Back to root
      run: cd ..
    - name: Build Docker image
      run: |
        docker build -t demo-springboot:latest .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push demo-springboot:latest
